### ISSUE TITLE
Mixed CPAN Testers results (related to XML parser?)

### ISSUE THREAD

**Issue by eserte** [apcros/Drac-Perl#3]
t/client.t fails on some CPAN Testers systems, see http://matrix.cpantesters.org/?dist=DracPerl-Client+0.10
It seems that this depends on the used XML parser in XML::Simple: if XML::Parser is used, then it passes, if XML::SAX is used, then it fails.

**Comment by apcros** [comment]
Hmm, I'll have a closer look at that and try to fix that. Thanks for raising that !

**Comment by apcros** [comment]
Fixed with 0.20
